version: '3.4'

services:
  catalogdb:
    container_name: catalogdb
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  cartdb:
    container_name: cartdb
    restart: always
    ports:
      - "6379:6379"

  discountdb:
    container_name: discountdb
    environment:
      -  POSTGRES_USER=admin
      - "POSTGRES_PASSWORD=Nappyboy@247"
      - "POSTGRES_DB=DiscountDb"
    restart: always
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql

  orderdb:
    container_name: orderdb
    environment:
        MSSQL_SA_PASSWORD: "Nappyboy@247"
        ACCEPT_EULA: "Y"
        MSSQL_PID : "Express"
    restart: always
    ports:
        - "1433:1433"

  rabbitmq:
    container_name: rabbitmq
    restart: always
    ports:
        - "5672:5672"
        - "15672:15672"

  pgadmin:
    container_name: pgadmin
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@docker.com
      - PGADMIN_DEFAULT_PASSWORD=Nappyboy@247
    restart: always
    ports:
        - "5050:80"
    volumes:
      - pgadmin_data:/root/.pgadmin

  portainer:
    container_name: portainer
    restart: always
    ports:
      - "8082:8080"
      - "9000:9000"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer_data:/data

  catalogue.api:
    container_name: catalogue.api
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - "DatabaseSettings:ConnectionString=mongodb://catalogdb:27017"
    depends_on:
      - catalogdb
    ports:
      - "8080:8080"

  cart.api:
    container_name: cart.api
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - "CacheSettings:ConnectionString=cartdb:6379"
      - "GrpcSettings:DiscountUrl=http://192.168.1.142:8084"
    depends_on:
      - cartdb
    ports:
      - "8081:8080"

  discount.api:
    container_name: discount.api
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - "DatabaseSettings:ConnectionString=Server=discountdb;Port=5432;Database=DiscountDb;User Id=admin;Password=Nappyboy@247;"
    depends_on:
        - discountdb
    ports:
      - "8083:8080"

  discount.grpc:
    container_name: discount.grpc
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - "DatabaseSettings:ConnectionString=Server=discountdb;Port=5432;Database=DiscountDb;User Id=admin;Password=Nappyboy@247;"
    depends_on:
      - discountdb
    ports:
      - "8084:8080"

  ordering.api:
    container_name: ordering.api
    environment:
        - ASPNETCORE_ENVIRONMENT=Development
        - "ConnectionStrings:OrderingConnectionString=Server=orderdb;Database=OrderDb;User Id=sa;Password=Nappyboy@247;MultipleActiveResultSets=true;TrustServerCertificate=True"            
        - "EventBusSettings:HostAddress=amqp://guest:guest@rabbitmq:5672"            
    depends_on:
        - orderdb
    ports:
        - "8085:8080"

  ocelotapi.gateway:
    container_name: ocelotapi.gateway
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - "ElasticConfiguration:Uri=http://elasticsearch:9200"
    depends_on:
        - catalogue.api
        - cart.api
        - discount.api
        - ordering.api
    ports:
      - "8086:8080"