version: '3.4'

services:
  catalogdb:
    image: mongo

  cartdb:
    image: redis:alpine

  pgadmin:
    image: dpage/pgadmin4  

  discountdb:
    image: postgres

  portainer:
    image: portainer/portainer-ce

  catalogue.api:
    image: ${DOCKER_REGISTRY-}catalogueapi
    build:
      context: .
      dockerfile: Services/Catalogue.API/Dockerfile

  cart.api:
    image: ${DOCKER_REGISTRY-}cartapi
    build:
      context: .
      dockerfile: Services/Cart.API/Dockerfile

  discount.api:
    image: ${DOCKER_REGISTRY-}discountapi
    build:
      context: .
      dockerfile: Services/Discount/Discount.API/Dockerfile

  discount.grpc:
    image: ${DOCKER_REGISTRY-}discountgrpc
    build:
      context: .
      dockerfile: Services/Discount/Discount.Grpc/Dockerfile

volumes:
 mongo_data:
 portainer_data:
 postgres_data:   
 pgadmin_data:

