version: '3.4'

services:
  catalogdb:
    image: mongo


  catalogue.api:
    image: ${DOCKER_REGISTRY-}catalogueapi
    build:
      context: .
      dockerfile: Services/Catalogue.API/Dockerfile

volumes:
 mongo_data: