version: '3.4'

services:
  catalogdb:
    image: mongo

  cartdb:
    image: redis:alpine

  portainer:
    image: portainer/portainer-ce

  catalogue.api:
    image: ${DOCKER_REGISTRY-}catalogueapi
    build:
      context: .
      dockerfile: Services/Catalogue.API/Dockerfile

  cart.api:
    image: ${DOCKER_REGISTRY-}cartapi
    build:
      context: .
      dockerfile: Services/Cart.API/Dockerfile

volumes:
 mongo_data:
 portainer_data: